### ISSUE TITLE
User doesn't have access for metadata callbacks

### ISSUE THREAD

**Issue by nerakulous** [Teradata/sqlalchemy-teradata#43]
IT policy prevents business users from accessing any dbc tables or any other tables equivalent to dbc.columns or dbc.tables. Users are required to fully qualify all objects but the metadata callbacks used by SQLAlchemy prevent them from using the tool. 

It would be useful to turn off metadata callbacks and allow functions that can still run as long as objects are fully qualified.

**Comment by sandan** [comment]
@nerakulous Is there an example you can provide so I can better understand what is failing? 

The answer to your question is that it depends on what you are trying to do. The metadata callbacks are needed for SQLAlchemy to function properly. Take for example the method in  [has_table](https://github.com/Teradata/sqlalchemy-teradata/blob/master/sqlalchemy_teradata/dialect.py#L110). This needs to be defined so that logic in the SQLAlchemy package can call it. Currently, for Teradata it is implemented by querying the “dbc.tablesvx” view.
 
We can change the view or look in the default database by default. Depending on your use case this may or may not be what you want.

**Comment by danielpoon** [comment]
@nerakulous - I went into dialects.py in the /site-package/sqlalchemy_teradata directory and commented the one that's causing me problem. Somehow it only calls the DBCInfoV. This block of code is towards the very end of the script that attempts to get the version of Teradata. I changed the code to:

res = '15'

That's it and everything worked. This is a workaround.
