### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by deezelmunky** [Teradata/sqlalchemy-teradata#84]
from sqlalchemy import create_engine
user = 'xxxx'
pasw=xxxx
host = 'xxxx'

# connect
td_engine = create_engine('teradata://'+ user +':' + pasw + '@'+ host + ':22/')

# execute sql
sql = 'select * from dbc.usersV'
result = td_engine.execute(sql)

I picked this piece of code from https://downloads.teradata.com/tools/articles/teradata-sqlalchemy-introduction

And Im inputting some Teradata user credentials........

This is the error im getting:

Traceback (most recent call last):
  File "SQL_ALCHEMY.py", line 3, in <module>
    pasw=xxxx
NameError: name 'xxxx' is not defined

**Comment by deezelmunky** [comment]
After a bit of research it seems like I have to incorporate a driver name into the create_engine function. Any ideas on how to do that? The driver name in this case would be Teradata Database ODBC Driver 16.10

**Comment by sandan** [comment]
This problem: `NameError: name 'xxxx' is not defined` is due to the fact that you have not defined a variable called xxxx.

I highly recommend you install the following:
`pip install teradatasqlalchemy`

See: https://pypi.org/project/teradatasqlalchemy/

This package implements the teradatasql dialect which is more up to date and does not require ODBC, making it much easier to install. It is available for Mac, Windows, and some Linux flavors (see the pypi link).

**Comment by Pallavi7389** [comment]
This is working.

```
import sqlalchemy
td_engine = sqlalchemy.create_engine("teradata://username:Pwd@DNS_NAME/database_name?driver=Teradata Database ODBC Driver 16.20")
```
